hubg/gamehub/urls.py
from django.conf.urls import patterns, include, url


from gamehub import views



urlpatterns = patterns ('',


	# Blank after gamehub/ so this will be index page
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.GameDetailView.as_view(), name='gamedetail'),

)

hubg/hubg/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hubg.views.home', name='home'),
    # url(r'^hubg/', include('hubg.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^gamehub/',include('gamehub.urls',namespace='gamehub')),
)

hubg/gamehub/models.py
from django.db import models

# Create your models here.

class Game(models.Model):
	name = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	age_limit = models.IntegerField(default=18)


	def __unicode__(self):
		return self.name

class GameDescription(models.Model):
	game = models.ForeignKey(Game)
	description = models.CharField(max_length=500)

	gen_RPG = 'RPG'
	gen_MMO = 'MMO'
	gen_ACT = 'ACT'
	gen_STRAT = 'STRAT'
	gen_RTS = 'RTS'

	GENRE_CHOICES = (
		(gen_RPG, 'RolePlayingGame'),
		(gen_MMO, 'MassiveMultiplayerOnline'),
		(gen_ACT, 'Action'),
		(gen_STRAT, 'Strategy'),
		(gen_RTS, 'RealTimeStrategy'),
	)

	genre = models.CharField(max_length=3, choices=GENRE_CHOICES, default= gen_RPG)


	def __unicode__(self):
		return self.description


class GameReview(models.Model):
	game = models.ForeignKey(Game)
	reviewDescription = models.CharField(max_length=500, default= '')
	reviewTitle = models.CharField(max_length=100, default= '')

	def __unicode__(self):
		return self.reviewTitle

class GameRating(models.Model):
	gameReview = models.ForeignKey(GameReview)
	rating = models.IntegerField(default=3)

	def __unicode__(self):
		return str(self.rating)
		# Note:: This will cause errors if left as an int because unicode conversion expects string

hubg/gamehub/views.py
# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.template import Context, loader
from django.shortcuts import render, get_object_or_404 # 404 is Http response for not found
from django.views import generic
from django.utils import timezone

from gamehub.models import *

class IndexView(generic.ListView):
	template_name = 'gamehub/index.html'
	model = Game


	def get_context_data(self, **kwargs):
		# kw args allows for key/value pairs of data to be passed in a function and then
		# wrapped into a single dictionary variable called kwargs	
		context = super(IndexView, self).get_context_data(**kwargs)
		context['curTime'] = timezone.now()
		context['dev'] = 'Crebstar'
		context['title'] = 'Game List'
		context['games'] = Game.objects.all()
		return context;


class HubTestMixin(object):
	'''
	Testing out mixins
	'''
	numberTest = 5

	def get_context_data(self, **kwargs):
		kwargs.update({
			'lama': 'TheDailyLama',
			'numberTest': self.numberTest
			})
		return super(HubTestMixin, self).get_context_data(**kwargs)

class GameDetailView(HubTestMixin, generic.DetailView):
	'''
	DetailViews exist for the purpose of displaying detail on an
	individual object. It inherits from the SingleObjectMixin which
	provides the get_object() method which figures out the object based on
	the url of the request (looks for slug or pk)
	'''
	template_name = 'gamehub/gamedetail.html'
	model = Game

	def get_context_data(self, **kwargs):
		context = super(GameDetailView, self).get_context_data(**kwargs)

		#  This is most likely terrible practice
		#  tomorrow lookup how to do overriding of get_queryset
		#  This doesn't throw a 404 
		context['gameSelected'] = Game.objects.get(pk=int(self.kwargs['pk']))
		context['gameDescription'] = context['gameSelected'].gamedescription_set.get(pk=int(self.kwargs['pk']))

		return context


	

hubg/gamehub/templates/gamehub/gamedetail.html
{% extends "gamehub/layout.html" %}




{% block main %}
<h3> Game Detail Page <h3>

<div>
	<h2 id="gameTitle"> {{ gameSelected.name }}	<h2>

	<p id="gameGenre"> {{ gameDescription.genre }} </p>

	<p id="gameDescription"> {{ gameDescription.description }} </p>

	<br>


</div>

<a> Go back to GameHub Game Listing </a>
<p id="testingLess"> Hey now go pet the {{ lama }} </p>

{% endblock %}

hubg/gamehub/templates/gamehub/index.html
{% extends "gamehub/layout.html" %}


{% block title %} {{ title }} {% endblock %}

{% block main %} 

<div class="mainBodyGameHub">

	<h3 class="GameHub titles"> 	GameHub - {{ title }} </h3>
	<ul class="gameHubList">
		{% for game in games %}
			
			<li class="gamehubGameItem"> 
				<a href="{% url 'gamehub:gamedetail' game.id %}">
					{{ game.name }}
				</a> 
			</li>
		{% endfor %}

	</ul>


</div>

<div id="gameHubFooter">

	<br>
	<br>

	<p> GameHub developed by {{ dev }} </p> 

	<br>
	<br>

</div>

{% endblock %}

hubg/gamehub/templates/gamehub/layout.html
{# This is so django-compressor can work #}
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">

<head>
	<title> {% block title %} Welcome {% endblock %} GameHub Rev </title>

	{% if debug %}
	
	{# rel defines the relationship between this document and the linked sheet #}
		<link rel="stylesheet/less" href="{{ STATIC_URL }}gamehub/less/gamehub.less" type="text/less">
		<script src="{{ STATIC_URL }}gamehub/js/less-1.3.0.min.js"></script>
	
	{% else %}
	{% compress css %}
	
	<link rel="stylesheet" type="text/less" media="all" href="{{ STATIC_URL }}less/style.less" />
	{% endcompress %}
	{% endif %}



</head>

<body>
	
	{% block navbar %}

	<!-- The nav tag is a new HTML tag which represents a collection of links -->
	<nav id="util-nav" class="navbar site-nav">
		<div class="container">
			<div class="row">
				<div class="span12">
					<div class="navbar">
						<div class="navbar-inner">
							<ul class="nav">
								<li>
									<a href="{% url 'gamehub:index' %}">GameHub</a>
								</li>
								<li>
									<a href="">About</a>
								</li>
								<li>
									<a href="">Contact Us</a>
								</li>
						</div>
					</div>



				</div>
			</div>
		</div>

	</nav>

	{% endblock %}

	{% block main %}
		<h1>Please extend main block </h1>
		<p> If you can see this text, then you need to extend the main block in your template </p>
	{% endblock %}

</body>

</html>